config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new', as: 'new_task'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  post'/tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch '/tasks/:id', to: 'tasks#update', as: 'update'
  delete '/tasks/:id', to: 'tasks#delete', as: 'delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new; end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def delete
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<form action="/tasks/<%=@task.id%>" method="post">
  <input name="_method" type="hidden" value="patch"/>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
  <span class="ml-3">Title</span>
  <div style="max-width: 250px" class="ml-3 mt-2">
    <input class="form-control" type="text" name="task[title]" value="<%= @task.title%>"><br>
    <span>Description</span>
    <textarea class="form-control mt-2" id="exampleFormControlTextarea1" rows="2" name="task[details]"><%= @task.details %></textarea>
    <input type="checkbox" name="task[completed]">Completed <br>
    <input type="submit" class="btn btn-success mt-3">
  </div>
</form>

app/views/tasks/index.html.erb
<div class="container">
<h1>Tasks List</h1>
<% @tasks.each do |task| %>
  <input type="checkbox" <%= task.completed ? 'checked' : ''%>> <%= link_to "#{task.title}", task_path(task) %>
  <%= link_to "Delete", delete_path(task), method: :delete, data: { confirm: "Are you sure?" } %> <br>
<%end%>



<%= link_to new_task_path do %>
  <button type="button" class="btn btn-primary">Create new Task</button>
<%end%>
</div>

app/views/tasks/new.html.erb
<h2 class="ml-3 mt-3">Create a new task</h2>
<form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
  <span class="ml-3">Title</span>
  <div style="max-width: 250px" class="ml-3 mt-2">
    <input class="form-control" type="text" name="task[title]"> <br>
    <span>Description</span>
    <textarea class="form-control mt-2" id="exampleFormControlTextarea1" rows="2" name="task[details]"></textarea>
    <input type="submit" class="btn btn-success mt-3">
  </div>
</form>

app/views/tasks/show.html.erb
<div class="container">
<h1><%= @task.title%></h1>
<p><%= @task.details %></p>
<input type="checkbox">This task is not completed yet> <br> <br>
<%= link_to 'Back to Tasks', tasks_path %>
<%= link_to 'Edit this task', edit_task_path %>
</div>